/*
 * Copyright 2010 SPeCS Research Group.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License. under the License.
 */

/*
 * HeapWindow.java
 * 
 * Created on 24/Jun/2010, 16:08:44
 */

package pt.up.fe.specs.util.utilities.heapwindow;

import java.awt.EventQueue;
import java.io.Serial;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import pt.up.fe.specs.util.SpecsSystem;
import pt.up.fe.specs.util.SpecsSwing;

/**
 * Shows a Swing frame with information about the current and maximum memory of
 * the heap.
 *
 * @author Ancora Group <ancora.codigo@gmail.com>
 */
public class HeapWindow extends JFrame {

    @Serial
    private static final long serialVersionUID = 1L;

    private static final long UPDATE_PERIOD_MS = 500;

    /**
     * If true, UI components and timer were initialized. False when running in a
     * headless environment where Swing windows cannot be displayed.
     */
    private final boolean enabled;

    /** Creates new form HeapWindow */
    public HeapWindow() {
        boolean headless = SpecsSwing.isHeadless();
        this.enabled = !headless;

        if (headless) {
            // Headless - do not initialize Swing components or timers
            this.timer = null;
            return;
        }

        initComponents();
        long heapMaxSize = Runtime.getRuntime().maxMemory();

        long maxSizeMb = (long) (heapMaxSize / (Math.pow(1024, 2)));
        this.jLabel2.setText(this.jLabel2Prefix + maxSizeMb + "Mb");

        final MemProgressBarUpdater memProgressBar = new MemProgressBarUpdater(this.jProgressBar1);
        this.timer = new Timer();
        this.timer.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                try {
                    memProgressBar.doInBackground();
                } catch (Exception ex) {
                    Logger.getLogger(HeapWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, 0, HeapWindow.UPDATE_PERIOD_MS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jProgressBar1 = new JProgressBar();
        this.jLabel1 = new JLabel();
        this.jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        this.jLabel1.setText("Heap Use/Size");

        this.jLabel2.setText("Max. Size:");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addComponent(this.jProgressBar1,
                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                172, Short.MAX_VALUE)
                                                                        .addContainerGap())
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addComponent(this.jLabel1)
                                                                        .addPreferredGap(
                                                                                LayoutStyle.ComponentPlacement.RELATED,
                                                                                19, Short.MAX_VALUE)
                                                                        .addComponent(this.jLabel2)
                                                                        .addContainerGap(44, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(this.jLabel1)
                                                        .addComponent(this.jLabel2))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(this.jProgressBar1, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void run() {
        if (!enabled) {
            return; // No-op in headless environments
        }

        EventQueue.invokeLater(() -> {
            setTitle("Heap - " + SpecsSystem.getProgramName());
            setVisible(true);
        });
    }

    public void close() {
        if (!enabled) {
            return; // Nothing to close
        }
        EventQueue.invokeLater(() -> {
            if (HeapWindow.this.timer != null) {
                HeapWindow.this.timer.cancel();
            }
            dispose();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    private final String jLabel2Prefix = "Max. Size: ";
    private final Timer timer;
}
