/*
 * Copyright 2021 SPeCS Research Group.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License. under the License.
 */

package pt.up.fe.specs.util;

/**
 * Enum for specifying DOT rendering formats.
 * <p>
 * Used for selecting output formats in graph rendering utilities.
 * </p>
 */
public enum DotRenderFormat {

    /**
     * PNG format for rendering DOT files.
     */
    PNG,

    /**
     * SVG format for rendering DOT files.
     */
    SVG;

    /**
     * Gets the flag associated with the rendering format.
     * <p>
     * The flag is used in graph rendering utilities to specify the output format.
     * </p>
     *
     * @return the flag for the rendering format
     */
    public String getFlag() {
        return "-T" + name().toLowerCase();
    }

    /**
     * Gets the file extension associated with the rendering format.
     * <p>
     * The extension is used for naming output files generated by graph rendering utilities.
     * </p>
     *
     * @return the file extension for the rendering format
     */
    public String getExtension() {
        return name().toLowerCase();
    }
}
