# This workflow will build and test all Gradle-migrated projects in specs-java-libs every day at midnight
# It will also run on every push and pull request

name: nightly

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  contents: write

env:
  JAVA_VERSION: 17

jobs:
  build-gradle-projects:
    name: Build & Test Gradle Projects Sequentially
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specs-java-libs
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          dependency-graph: generate-and-submit

      - name: Build and test all Gradle projects sequentially
        run: |
          set -e
          projects=(
            AsmParser
            CommonsCompressPlus
            CommonsLangPlus
            GearmanPlus
            GitPlus
            Gprofer
            GsonPlus
            GuiHelper
            JacksonPlus
            JadxPlus
            JavaGenerator
            jOptions
            JsEngine
            LogbackPlus
            SpecsUtils
            SymjaPlus
            tdrcLibrary
            XStreamPlus
          )
          for project in "${projects[@]}"; do
            echo "\n===== Building and testing $project ====="
            cd "$project"
            gradle build test
            cd -
          done
        env:
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          summary: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-builds
          path: '**/build/libs/'
